export const SET_CURRENT = 'SET_CURRENT';
export const CLEAR_CURRENT = 'CLEAR_CURRENT';

export const SET_LOADING = 'SET_LOADING';

export const GET_LESSON_TYPES = 'GET_LESSON_TYPES';
export const ADD_LESSON_TYPE = 'ADD_LESSON_TYPE';
export const UPDATE_LESSON_TYPE = 'UPDATE_LESSON_TYPE';
export const LESSON_TYPE_ERROR = 'LESSON_TYPE_ERROR';
