//CURRENT
export const SET_CURRENT = 'SET_CURRENT';
export const CLEAR_CURRENT = 'CLEAR_CURRENT';

//LOADING
export const SET_LOADING = 'SET_LOADING';

//LESSON_TYPES
export const GET_LESSON_TYPES = 'GET_LESSON_TYPES';
export const ADD_LESSON_TYPE = 'ADD_LESSON_TYPE';
export const UPDATE_LESSON_TYPE = 'UPDATE_LESSON_TYPE';
export const DELETE_LESSON_TYPE = 'DELETE_LESSON_TYPE';
export const LESSON_TYPE_ERROR = 'LESSON_TYPE_ERROR';

//CALENDAR_SLOTS
export const GET_CALENDAR = 'GET_CALENDAR';
export const ADD_VACANT_SLOT = 'ADD_VACANT_SLOT';
export const DELETE_VACANT_SLOT = 'DELETE_VACANT_SLOT';
export const CALENDAR_ERROR = 'CALENDAR_ERROR';
export const SAVE_SCHEDULE = 'SAVE_SCHEDULE';
