//LOADING
export const SET_LOADING = 'SET_LOADING';

//LESSON_TYPES
export const GET_LESSON_TYPES = 'GET_LESSON_TYPES';
export const ADD_LESSON_TYPE = 'ADD_LESSON_TYPE';
export const UPDATE_LESSON_TYPE = 'UPDATE_LESSON_TYPE';
export const DELETE_LESSON_TYPE = 'DELETE_LESSON_TYPE';
export const LESSON_TYPE_ERROR = 'LESSON_TYPE_ERROR';
export const SET_CURRENT_LESSON_TYPE = 'SET_CURRENT_LESSON_TYPE';
export const CLEAR_CURRENT_LESSON_TYPE = 'CLEAR_CURRENT_LESSON_TYPE';

//CALENDAR_SLOTS
export const GET_CALENDAR = 'GET_CALENDAR';
export const ADD_VACANT_SLOT = 'ADD_VACANT_SLOT';
export const DELETE_VACANT_SLOT = 'DELETE_VACANT_SLOT';
export const CALENDAR_ERROR = 'CALENDAR_ERROR';

//SCHEDULES
export const GET_SCHEDULES = 'GET_SCHEDULES';
export const ADD_SCHEDULE = 'ADD_SCHEDULE';
export const APPLY_SCHEDULE = 'APPLY_SCHEDULE';
export const DELETE_SCHEDULE = 'DELETE_SCHEDULE';
export const SCHEDULE_ERROR = 'SCHEDULE_ERROR';
