//LOADING
export const SET_LOADING = 'SET_LOADING';

//LESSON_TYPES
export const GET_LESSON_TYPES = 'GET_LESSON_TYPES';
export const ADD_LESSON_TYPE = 'ADD_LESSON_TYPE';
export const UPDATE_LESSON_TYPE = 'UPDATE_LESSON_TYPE';
export const DELETE_LESSON_TYPE = 'DELETE_LESSON_TYPE';
export const LESSON_TYPE_ERROR = 'LESSON_TYPE_ERROR';
export const SET_CURRENT_LESSON_TYPE = 'SET_CURRENT_LESSON_TYPE';
export const CLEAR_CURRENT_LESSON_TYPE = 'CLEAR_CURRENT_LESSON_TYPE';
export const SET_LOADING_LESSON_TYPE = 'SET_LOADING_LESSON_TYPE';

//CALENDAR_SLOTS
export const GET_CALENDAR = 'GET_CALENDAR';
export const ADD_VACANT_SLOTS = 'ADD_VACANT_SLOTS';
export const DELETE_VACANT_SLOTS = 'DELETE_VACANT_SLOTS';
export const CALENDAR_ERROR = 'CALENDAR_ERROR';
export const SET_DAYS_ON_DISPLAY = 'SET_DAYS_ON_DISPLAY';
export const SET_LOADING_CALENDAR = 'SET_LOADING_CALENDAR';

//SCHEDULES
export const GET_SCHEDULES = 'GET_SCHEDULES';
export const ADD_SCHEDULE = 'ADD_SCHEDULE';
export const APPLY_SCHEDULE = 'APPLY_SCHEDULE';
export const DELETE_SCHEDULE = 'DELETE_SCHEDULE';
export const SCHEDULE_ERROR = 'SCHEDULE_ERROR';

//STUDENTS
export const GET_STUDENTS = 'GET_STUDENTS';
export const DELETE_STUDENT = 'DELETE_STUDENT'; //GDPR concern
export const SET_CURRENT_STUDENT = 'SET_CURRENT_STUDENT';
export const CLEAR_CURRENT_STUDENT = 'CLEAR_CURRENT_STUDENT';
export const STUDENT_ERROR = 'STUDENT_ERROR';

//LESSONS
export const GET_LESSONS = 'GET_LESSONS';
export const UPDATE_LESSON = 'UPDATE_LESSON';
export const LESSON_ERROR = 'LESSON_ERROR';

//AUTH
export const REGISTER_SUCCESS = 'REGISTER_SUCCESS';
export const REGISTER_FAIL = 'REGISTER_FAIL';
export const USER_LOADED = 'USER_LOADED';
export const AUTH_ERROR = 'AUTH_ERROR';
export const LOGIN_SUCCESS = 'LOGIN_SUCCESS';
export const LOGIN_FAIL = 'LOGIN_FAIL';
export const LOGOUT = 'LOGOUT';
export const SET_LOADING_AUTH = 'SET_LOADING_AUTH';

//BOOKING
export const SET_CURRENT_BOOKING = 'SET_CURRENT_BOOKING';
export const CLEAR_CURRENT_BOOKING = 'CLEAR_CURRENT_BOOKING';
export const SET_SELECTED_SLOTS = 'SET_SELECTED_SLOTS';
export const BOOKING_ERROR = 'BOOKING_ERROR';

export const ADD_REQUEST_TO_CALENDAR = 'ADD_REQUEST_TO_CALENDAR';
export const ACCEPT_BOOK_REQUEST = 'ACCEPT_BOOK_REQUEST';
export const DECLINE_BOOK_REQUEST = 'DECLINE_BOOK_REQUEST';

//TEACHER
export const GET_TEACHER_INFO = 'GET_TEACHER_INFO';
export const GET_TEACHER_ERROR = 'GET_TEACHER_ERROR';
